version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: qrart-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: qrart
    ports:
      - "3307:3306"
    volumes:
      - qrart_data:/var/lib/mysql

volumes:
  qrart_data:
